Repository Y3-S1-project-group/Medicare-backend, pull requests merged in 2024-10, with the labels that each got.

#2 backend of Staff management added
  models/Staff.js
  routes/Staffs.js
  server.js
Labels: documentation

#4 appoinment backend
  models/Appoinments.js
  package-lock.json
  package.json
  routes/AppoinmentRouter.js
  server.js
Labels: feature

#6 It22352576medicine
  routes/reportRouter.js
  server.js
Labels: documentation, feature

#10 Dev
  controllers/adminControllers.js
  controllers/authController.js
  models/Appoinments.js
  models/Patient.js
  models/Staff.js
  models/User.js
  package-lock.json
  package.json
  routes/AppoinmentRouter.js
  routes/Staffs.js
  routes/adminRoutes.js
  routes/auth.js
  routes/authRoutes.js
  routes/reportRouter.js
  server.js
Labels: good first issue

#12 ok
  routes/auth.js
  server.js
Labels: feature

#14 It22202468/user management
  controllers/adminControllers.js
  controllers/authController.js
  models/patientModel.js
  package-lock.json
  package.json
  routes/adminRoutes.js
  routes/auth.js
  routes/authRoutes.js
  routes/patientRoutes.js
  server.js
  tests/appointment.test.js
  tests/patientRoutes.test.js
Labels: feature
